online_ordering_enabled: false
social_media:
  facebook_url: https://www.facebook.com/harlowesfrenchdip
  twitter_url: https://twitter.com/harlowesdips
  instagram_url: https://www.instagram.com/harlowesfrenchdip/
  yelp_url: http://www.yelp.com/biz/harlowes-french-dip-pasadena-4
location:
  phone_number: 626-535-0985
  fax: 626-535-0985
  address_line_1: 43 E Union Street
  address_line_2: Pasadena, CA 91103
  email: info@harlowesfrenchdip.com
send_contact_to: info@harlowesfrenchdip.com
ordering_disabled_notice: Online ordering is currently disabled
